development:
  adapter: postgresql
  encoding: unicode
  database: flix_development
  pool: 5
  username: AbuJega
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: flix_test
  pool: 5
  username: AbuJega
  password: pass

